config-service:
  image: romeomaryns/config-service
  environment:
   - SPRING_PROFILES_ACTIVE=docker
   - DOCKER_IP=$DOCKER_IP
  ports:
   - 8888:8888
hystrix-dashboard:
  image: romeomaryns/hystrix-dashboard
  environment:
   - SPRING_PROFILES_ACTIVE=docker
   - DOCKER_IP=$DOCKER_IP
  ports:
   - 6161:6161
mysql:
  image: mysql:5.7
  ports:
   - 3306:3306
  environment:
   - MYSQL_ROOT_PASSWORD=dbpass
   - MYSQL_DATABASE=dev
neo4j:
  image: neo4j:2.3
  ports:
   - 7474:7474
  environment:
   - NEO4J_AUTH=none
mongo:
  image: mongo:3.3
  ports:
   - 27017:27017
redis:
  image: redis:3.0
  ports:
   - 6379:6379
user-service:
  image: romeomaryns/user-service
  ports:
   - 8181:8181
  links:
   - mysql
   - discovery-service
   - config-service
  environment:
   - SPRING_PROFILES_ACTIVE=docker
   - DOCKER_IP=$DOCKER_IP
discovery-service:
  image: romeomaryns/discovery-service
  ports:
   - 8761:8761
  environment:
   - SPRING_PROFILES_ACTIVE=docker
   - DOCKER_IP=$DOCKER_IP
edge-service:
  image: romeomaryns/edge-service
  ports:
   - 9999:9999
  links:
   - user-service
   - discovery-service
   - config-service
  environment:
   - SPRING_PROFILES_ACTIVE=docker
   - DOCKER_IP=$DOCKER_IP
account-service:
  image: romeomaryns/account-service
  links:
   - user-service
   - discovery-service
   - config-service
   - mysql
  environment:
   - SPRING_PROFILES_ACTIVE=docker
   - DOCKER_IP=$DOCKER_IP
inventory-service:
  image: romeomaryns/inventory-service
  links:
   - neo4j
   - discovery-service
   - config-service
  environment:
   - SPRING_PROFILES_ACTIVE=docker
   - DOCKER_IP=$DOCKER_IP
order-service:
  image: romeomaryns/order-service
  links:
   - mongo
   - discovery-service
   - config-service
   - user-service
  environment:
   - SPRING_PROFILES_ACTIVE=docker
   - DOCKER_IP=$DOCKER_IP
catalog-service:
  image: romeomaryns/catalog-service
  links:
   - redis
   - mysql
   - discovery-service
   - config-service
  environment:
   - SPRING_PROFILES_ACTIVE=docker
   - DOCKER_IP=$DOCKER_IP
shopping-cart-service:
  image: romeomaryns/shopping-cart-service
  links:
   - mysql
   - discovery-service
   - config-service
   - user-service
  environment:
   - SPRING_PROFILES_ACTIVE=docker
   - DOCKER_IP=$DOCKER_IP
gateway:
  image: romeomaryns/gateway
  ports:
   - 8787:8787
  links:
   - discovery-service
   - config-service
   - user-service
   - edge-service
  environment:
   - SPRING_PROFILES_ACTIVE=docker
   - DOCKER_IP=$DOCKER_IP
